// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emplagwsoqmbiunstere.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtcGxhZ3dzb3FtYml1bnN0ZXJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3MDE4MzcsImV4cCI6MjA1MDI3NzgzN30.R29M23ndPcutrekx7oqM6Mlag9w6gwRwL3vw1lrFVuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);